openapi: 3.0.1
info:
    title: 旅游路径规划
    description: 实现个性化的旅游路线规划功能，可以根据提供的预算以及目标旅游地点规划出行程安排，并可以规划每个目的地之间的路线，包括驾驶路线、公共交通路线，最后以一个PPT的格式展示出来个性化的英文单词本，可以增加、删除和浏览单词本中的单词，背单词时从已有单词本中随机抽取单词生成句子或者段落。
    version: "v3"
servers:
    - url: http://127.0.0.1:8081
paths:
     /get_destiantion:
        post:
            operationId: getdestination
            summary: 获得用户输入的目标旅游地
            responses:
                "200":
                    description: 成功获得目标旅游地信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getdestination"
    /get_navigation_needs:
        post:
            operationId: getnavigationneeds
            summary: 获得用户输入的导航区间
            responses:
                "200":
                    description: 成功获得导航区间信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getnavigationneeds"

components:
    schemas:
        getdestination:
            type: object
            required: [destination]
            properties:
                destination:
                    type: string
                    description: 目标旅游地
        getnavigationneeds:
            type: object
            required: [start_location,end_location]
            properties:
                start_location:
                    type: string
                    description: 起始地点
                end_location:
                    type: string
                    description: 终止地点
        